---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-app-id
data:
  app-id.json: |-
    {
      "trustedFacets": [
        {
          "version": {
            "major": 1,
            "minor": 0
          },
          "ids": [
            "https://bitwarden.fabrique-it.fr",
            "ios:bundle-id:com.8bit.bitwarden",
            "android:apk-key-hash:dUGFzUzf3lmHSLBDBIv+WaFyZMI"
          ]
        }
      ]
    }